### PR TITLE
Several improvements for Servicemesh scenarios

### PR DESCRIPTION
**Pull request by rafabene**
This PR contains the following improvements/fixes

- At the end of every scenarios, there is a link to https://developers.redhat.com/books/introducing-istio-service-mesh-microservices/
- Replace "Sleep 20" to wait OpenShift to be started in order to install the microservices and Istio
- The code is pulled from https://github.com/redhat-developer-demos/istio-tutorial/ using the *katacoda* branch.
- Removed /root/projects/incubator-openwhisk-devtools as it is not related to this scenario
- Rate Limiting is now working.

### CODE REVIEW

**Comment by mhausenblas** [comment]
I'm happy to merge it but would prefer a second pair of eyes, testing it.

**Comment by rafabene** [comment]
Thank you @mhausenblas. Who will test it?

**Comment by mhausenblas** [comment]
Not sure who @rafabene, any suggestions?

**Comment by rafabene** [comment]
Thanks 😄

**Pull request merged**
