### PR TITLE
Remove retired playgrounds

### PR DESCRIPTION
**Pull request by jdob**
The 4.6 and 4.4 playgrounds are appearing in the errors list as failure to start. To reduce that noise, let's remove the URLs to the playground themselves and let the user get a 404 instead.

### CODE REVIEW

**Review by ryanj — CHANGES_REQUESTED** [review]
I don't understand what the /archive path is for.  Isn't the git repo already an archive?

**Comment by jdob** [comment]
My fear was that we wouldn't easily be able to find them if we just used git for it, but you're right. Especially for these which I can't see a reason we'd ever want to restore. I'll update the PR.

**Comment by jdob** [comment]
Updated the PR to delete them entirely

**Review by ryanj — APPROVED** [review]
Looks good!

**Pull request merged**
