### PR TITLE
Update user-agent routing to use baggage

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://github.com/redhat-developer-demos/istio-tutorial/pull/81#issuecomment-396527538 

cc @rafabene

### CODE REVIEW

**Comment by pavolloffay** [comment]
Note that katacoda has to use modified images with the change.

**Comment by BenHall** [comment]
You reference which Images are required to be part of the base image in https://github.com/openshift-labs/learn-katacoda/blob/master/environments/openshift-middleware-3-7/scripts/istio-pull.sh

**Comment by pavolloffay** [comment]
Customer and preference spring boot images.

**Comment by rafabene** [comment]
These image are built based on the lastest source code.

**Comment by pavolloffay** [comment]
@rafabene Can it be merged?

**Comment by rafabene** [comment]
Yes 👍

**Comment by rafabene** [comment]
Any updates on this?

**Comment by pavolloffay** [comment]
@rafabene what updated do you mean?I think it just needs to be merged

**Pull request merged**
