### PR TITLE
wait for the assets to copy over

### PR DESCRIPTION
**Pull request by evanchooly**
The assets sometimes take a moment to show up.  Add a `sleep` to accommodate the delay

### CODE REVIEW

**Comment by BenHall** [comment]
Should/could very larger assets be moved to the base image?

**Comment by evanchooly** [comment]
in this case, it's just a bash script or two.  a 1 second sleep is *probably* sufficient but i went with 2 to be sure.

**Comment by BenHall** [comment]
Great! :)

**Comment by BenHall** [comment]
Thanks for the suggestions!

**Pull request closed without merging**
