### PR TITLE
updates for rhoar node.js GA

### PR DESCRIPTION
**Pull request by jamesfalkner**

### CODE REVIEW

**Comment by jamesfalkner** [comment]
@BenHall please review these changes. They are part of a few other changes that update the node.js bits and code to use latest GA versions released today.

This code commit and https://github.com/openshift-katacoda/rhoar-getting-started/pull/1 need to both be merged at or near the same time, and the base image updated to re-pull the latest code versions and update the pre-pulled docker image from the bucharest-gold nodejs one to the official node.js image (see updates to `middleware-pull.sh`). I hope you can review both and merge both at or near the same time!

**Comment by BenHall** [comment]
@jamesfalkner The environments on the self-paced labs for learn.openshift.com are being rebuilt now. When deployed, I'll merge. 

I'm not sure what I need to review for rhoar-getting-started. I also don't have permissions to merge on that repo

**Comment by jamesfalkner** [comment]
Isn’t part of the rebuild to clone the rhoar-getting-started repo? There are changes in there so If you rebuild before those changes are merged will you have to build again?

**Comment by BenHall** [comment]
In that case, it needs to be merged before I can rebuild the environment.

I didn't create the middleware image so i'm not sure how it works.

**Comment by jamesfalkner** [comment]
Ok I’m merge it now and notify you since the code still works with the existing Centos image..

**Comment by jamesfalkner** [comment]
Ok I merged the rhoar-getting-started repo , so you can now merge this PR and rebuild

**Comment by BenHall** [comment]
Thanks! Will rebuild everything over the weekend

**Pull request merged**
