### PR TITLE
Update primes in Quarkus Monitoring Scenarios

### PR DESCRIPTION
**Pull request by danieloh30**

### CODE REVIEW

**Comment by BenHall** [comment]
Thanks! Q: @jamesfalkner @danieloh30 Has this changed the URL used on developer.redhat? Need to know for routing traffic during the summit.

**Comment by jamesfalkner** [comment]
No it does not change the URL used to get to the scenario. It does change the URLs that are created via OpenShift Routes. Is that important for Summit?

**Comment by jamesfalkner** [comment]
Also this is not one of the scenarios featured at https://developers.redhat.com/summit/2020/self-paced so not sure if it matters for Summit.

**Comment by BenHall** [comment]
Ok great, no problem then! Just wanted to check as I spotted it :)

**Pull request merged**
