### PR TITLE
Operator SDK installation script for new custom Openshift 3-10 environment

### PR DESCRIPTION
**Pull request by tsanders-rh**
This script contains the necessary additional steps to install the operator-sdk tooling, as well as some env updates required for the training modules.  This script has been tested with the existing 3-10 environment.  We would like to get this built into a custom-env vs user having to run as first step in training.

### CODE REVIEW

**Comment by tsanders-rh** [comment]
@mhausenblas - Here is the PR we discussed in email.

**Comment by mhausenblas** [comment]
Great, thank you @tsanders-rh! @BenHall can you have a look pls and share if there's anything missing re custom image based on it?

**Comment by tsanders-rh** [comment]
@BenHall Thanks.  Assume there are additional steps beyond just making the script available on disk to have this run as part of the default 3-10 env? or another 3-10-op-sdk custom env?

**Comment by BenHall** [comment]
We're testing updates to 3.10 and will hopefully be live by Monday

**Comment by tsanders-rh** [comment]
@mhausenblas @BenHall Are the changes live in the 3.10 env?  If so, I am seeing some issues....should I file issues for those?

**Comment by BenHall** [comment]
Yes, please raise a new issue :)

**Comment by BenHall** [comment]
@tsanders-rh did you raise an issue with the changes you'd like to see?

**Comment by jwmatthews** [comment]
Issue filed in https://github.com/openshift-labs/learn-katacoda/issues/260

**Pull request merged**
