### PR TITLE
Use a versioned release of odo instead of latest

### PR DESCRIPTION
**Pull request by cmoulliard**
- Use a versioned release of odo instead of latest

### CODE REVIEW

**Comment by BenHall** [comment]
```
$ odo version
odo v0.0.16 (82968cb0)

Server: https://2886795304-8443-cykoria05.environments.katacoda.com:443
OpenShift: v3.11.0+0323629-61
Kubernetes: v1.11.0+d4cacc0
```

**Comment by jankleinert** [comment]
@cmoulliard Now that odo 0.0.17 has been released, users are going to get the following upgrade warning when they run odo commands:
```
---
A newer version of odo (version: 0.0.17) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/redhat-developer/odo/master/scripts/install.sh | sh
to update manually, or visit https://github.com/redhat-developer/odo/releases
---
If you wish to disable the update notifications, you can disable it by running
'odo utils config set UpdateNotification false'
```
To make the user experience smoother in the short term, would you be open to updating it to use 0.0.17 (hopefully there won't be another release before the end of next week)?

If you need it to be 0.0.16, that's okay too - I can just run the 'odo utils config set UpdateNotification false' in my init scripts.

**Comment by cmoulliard** [comment]
> would you be open to updating it to use 0.0.17

+1 to update it. You should perhaps create a regular task to update it every 2 weeks ;-)

**Comment by jankleinert** [comment]
Great - I'll create a PR today.

**Comment by jorgemoralespou** [comment]
You also need to execute: `odo utils config set UpdateNotification false` in the init script, so further new releases don't shout out that message

**Pull request merged**
