### PR TITLE
Updated the build script to cache maven artifacts more efficiently

### PR DESCRIPTION
**Pull request by tqvarnst**

### CODE REVIEW

**Comment by tqvarnst** [comment]
@BenHall This should be it. 😄 

Can you build it for the test environment so that I can verify it?

**Comment by tqvarnst** [comment]
@BenHall Any progress on this one?

**Comment by BenHall** [comment]
Sorry, missed the notification. Building a test environment now.

**Comment by tqvarnst** [comment]
Worked great, much fewer downloads happening during the scenario. Go ahead and merge and promote this to production. 

Thanks
Thomas

**Comment by BenHall** [comment]
Awesome! Nice work. Will merge tomorrow.

**Pull request closed without merging**
