### PR TITLE
add citrus basic (http) tutorial setup

### PR DESCRIPTION
**Pull request by tnobody**
This introduces a basic introduction to on integration testing with citrus framework in the (new) external section. The System under test is currently deployed in an external openshift cluster.

### CODE REVIEW

**Comment by mhausenblas** [comment]
Thanks @tnobody and can you please link to the preview in your own profile (something like https://katacoda.com/YOURUSERNAME/scenarios/)?

**Comment by tnobody** [comment]
Hi @mhausenblas Thanks for your comment, you can see an example of this at: https://www.katacoda.com/tnobody/scenarios/citurs-intro

**Comment by mhausenblas** [comment]
OK, thanks for providing this @tnobody and I've been able to successfully complete the scenario. Overall looking good, following some improvements I'd suggest:

- in the intro, link to Citrus and provide a short explanation what it is
- in step 2 the "Now, add the new HTTP client component and safe the file" can cause confusion, because the editor automatically saves the file
- while nice, remove the "please" in the instructions

My main issue is with the content: I don't see any relation to OpenShift, so I'm unsure how to proceed here.

**Comment by tnobody** [comment]
@mhausenblas thank for fro the recommendations. I pushed a new commit with the adapted contents (also on katacoda).
I tried to explain the relation to OpenShift in the intro very briefly. The SUT is also a deployed Spring-Boot application which runs on an Openshift cluster. 
It would also be possible to add an extra step where the participant have to deploy the application. But may be it could be a little bit to muh for the users since this tutorial should focus on "writing/running tests for application in openshift"... in further scenarios we could cover more complex things like deploy and run the test in openshift (buildpipelines) and so on. 
What do you think?

**Comment by gshipley** [comment]
@tnobody 

I ran through the scenario as well this morning and it looks great.  Nice work and nice use of the editor.  I think your suggestion of showing deployment to openshift in a new step is a good one to show the complete cycle from dev point of view.  You may need to switch out the base image used as it doesn't have the oc tool installed.

**Comment by tnobody** [comment]
@mhausenblas @gshipley 
Thank you for your feedback. I added a step where the user deploys the SUT on OpenShift. I use the image which is used by other deployment tutorials. Unfortunately I'm not able to test this setup since katacoda doesn't support the OS-Images.
Is there a way to launch the tutorial environment locally (using minishift or something similar)?

**Comment by mhausenblas** [comment]
Thanks @tnobody, I'm on travel today, will have a look tomorrow, latest.

**Comment by mhausenblas** [comment]
@tnobody so the step 0 looks great from the Markdown perspective and all I'd like to do before I merge this is really only once to walk through the scenario myself. I tried https://www.katacoda.com/tnobody/scenarios/citurs-intro but that seems to be not updated. Can you provide me with the new link please?

> Is there a way to launch the tutorial environment locally (using minishift or something similar)?

Unfortunately not.

**Comment by tnobody** [comment]
@mhausenblas Thank you.
I added step 0 to the tutorial on katacoda. Please keep in mind that the oc commands will not work in Katacoda. 
In addition I updated the `requestUrl` in the for the endpoint of this PR. It is now using the generated route to the app in Katacoda OpenShift.

**Comment by BenHall** [comment]
@tnobody The `oc` commands will work if you use the `openshift` image. What do you mean by `OS-Images`?

**Comment by tnobody** [comment]
@BenHall thank you for the hint! I just used the wrong image (and couldn't find the image in the Katacoda docs). 
With OS-Images, I meant the available images from Redhat-Kataoda environment which can be used in openshift-labs/learn-katacoda tutorials.
Katacoda is now updated but there are some issues with the deployment, which I need to fix.

**Comment by tnobody** [comment]
@mhausenblas 
Now the scenario on Katacoda works with OpenShift and all changes are pushed to this branch.

**Comment by mhausenblas** [comment]
Perfect, thanks @tnobody!

**Pull request merged**
