### PR TITLE
Add Servicemesh workshop

### PR DESCRIPTION
**Pull request by rafabene**
This substitutes #150 

@mhausenblas and @BenHall - This is rebased, and have existing istio workshop already moved. Tested and ready to be merged.

### CODE REVIEW

**Comment by mhausenblas** [comment]
LGTM, thanks!

**Comment by rafabene** [comment]
@mhausenblas How long does it take to be available at https://learn.openshift.com/ ?

**Comment by BenHall** [comment]
The content is live at https://learn.openshift.com/servicemesh

If you would like it to appear on the homepage, please update https://github.com/openshift-labs/learn-katacoda/blob/master/homepage-pathway.json

**Comment by rafabene** [comment]
@BenHall @mhausenblas Added to homepage in the PR https://github.com/openshift-labs/learn-katacoda/pull/155

**Pull request merged**
