### PR TITLE
fix #353 add pathway links

### LINKED ISSUE #353: Citrus tutorial is not linked / shown on learn.openshift.com
@mhausenblas 
The recently added tutorial for citrus-framework with openhift  (external/citrus/intro) is not shown on the website (learn.openshift.com)

### PR DESCRIPTION
**Pull request by tnobody**
This should fix #353

### CODE REVIEW

**Comment by BenHall** [comment]
Thanks, LGTM

**Comment by BenHall** [comment]
I'll leave to @mhausenblas to merge as I don't know if the titles/phasing are as the team want :)

**Comment by mhausenblas** [comment]
Besides the typo (`tehnoloiges`) … @BenHall will that show up in our categories?

**Comment by BenHall** [comment]
I was only checking the structure, sorry. Yes, that's what will appear in
the boxes.

**Comment by mhausenblas** [comment]
@BenHall re:

> Yes, that's what will appear in the boxes.

Can we not list it there? Is that an option?

**Comment by ZNicoZ** [comment]
@mhausenblas how would a user find the scenario without the linked boxes?

**Comment by mhausenblas** [comment]
@ZNicoZ fair question, only via the direct link. Oh well, I guess there are ATM not many other options. Merging now, we need to revisit this at some point in the future, though.

**Pull request merged**
