### PR TITLE
update to istio 0.6.0 in resilent-apps scenario

### PR DESCRIPTION
**Pull request by jamesfalkner**
Please review and merge @BenHall

### CODE REVIEW

**Comment by BenHall** [comment]
Thanks! Will merge once image has been deployed.

**Comment by BenHall** [comment]
Tested - Changes look good!

**Comment by BenHall** [comment]
Looks to have problems when setting the pods

```
$ oc logs grafana-4183644701-n5n8p
chown: changing ownership of '/data/grafana': Operation not permitted
chown: changing ownership of '/var/log/grafana': Operation not permitted

$ oc logs prometheus-3936029847-n69vg
level=info ts=2018-03-02T15:59:28.042770817Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0, branch=HEAD, revision=0a74f98628a0463dddc90528220c94de5032d1a0)"
level=info ts=2018-03-02T15:59:28.043184911Z caller=main.go:216 build_context="(go=go1.9.2, user=root@615b82cb36b6, date=20171108-07:11:59)"
level=info ts=2018-03-02T15:59:28.043202918Z caller=main.go:217 host_details="(Linux 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 prometheus-3936029847-n69vg (none))"
level=info ts=2018-03-02T15:59:28.046616511Z caller=web.go:380 component=web msg="Start listening forconnections" address=0.0.0.0:9090
level=info ts=2018-03-02T15:59:28.048324019Z caller=targetmanager.go:71 component="target manager" msg="Starting target manager..."
level=info ts=2018-03-02T15:59:28.048432628Z caller=main.go:314 msg="Starting TSDB"
level=error ts=2018-03-02T15:59:28.048563302Z caller=main.go:323 msg="Opening storage failed" err="mkdir data/: permission denied
```

**Comment by jamesfalkner** [comment]
are you sure all the lines from install-istio.sh were run? they add the necessary permissions to the grafana and prometheus serviceaccounts (anyuid and privileged scc's)

**Comment by BenHall** [comment]
Let me double check :)

**Comment by jamesfalkner** [comment]
k. in particular:
```
oc adm policy add-scc-to-user anyuid -z istio-grafana-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-prometheus-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z prometheus -n istio-system
oc adm policy add-scc-to-user privileged -z prometheus

oc adm policy add-scc-to-user anyuid -z grafana -n istio-system
oc adm policy add-scc-to-user privileged -z grafana
```

**Comment by BenHall** [comment]
Potentially an issue with the ordering?? If I return the commands first then it deploys. If I just run the script then it looks to have errors.

**Comment by jamesfalkner** [comment]
Thanks, that was it! I needed to have the permissions applied before creating the deployments. I've added another commit (and a merge commit). Let me know if I should squash and re-submit or you can take them as-is.

**Comment by rafabene** [comment]
Waiting this PR to get merged and the image with 0.6.0 to be deployed.

**Pull request merged**
