### PR TITLE
Removing operator-sdk install from course as it is already installed in 3.11 env

### PR DESCRIPTION
**Pull request by tsanders-rh**

### CODE REVIEW

**Comment by tsanders-rh** [comment]
@BenHall @mhausenblas - When you guys have a second, I'd like to get this merged.  This is just removing some of the work arounds that were introduced for kubecon workshop.  Thanks!

**Comment by BenHall** [comment]
Sorry, this got lost in the post-kubecon/pre-Christmas noise. 

It looks like the merge will only remove one of the downloads. I had expected to see the gcc install being removed if they are in the base-image. Such as:

https://github.com/openshift-labs/learn-katacoda/blob/master/ansibleop/ansible-operator-overview/env-init.sh#L15-L21

**Comment by tsanders-rh** [comment]
Good point.  Let me double check.

**Comment by tsanders-rh** [comment]
@BenHall - should be right now.  Course will just be busted till we get an updated env 3.11 image built.

**Comment by BenHall** [comment]
Let me check the environment before I merge then :)

**Comment by tsanders-rh** [comment]
@BenHall - Looks like new 3.11 image (with gcc installed) is available.  Can we proceed with merging this now?

**Pull request merged**
