### PR TITLE
Updating operator-sdk installation to v0.3.0 and fixing ansible-runner install.

### PR DESCRIPTION
**Pull request by tsanders-rh**

### CODE REVIEW

**Comment by tsanders-rh** [comment]
@BenHall @mhausenblas - If at all possible, I'd like to get this merged and a new 3.11 env image built this week.  Trying to clean things up from last week's operator training, so that we can advertise this online training publicly.  Thanks!

**Comment by BenHall** [comment]
It's been built and tested. It will be deployed this evening.

**Comment by tsanders-rh** [comment]
@BenHall - It doesn't appear that the latest script changes are in the 3.11 image.  Did a new image get deployed?

**Comment by tsanders-rh** [comment]
@BenHall - Thanks.  Looks good.

**Pull request merged**
