### PR TITLE
Adding new serverless eventing tutorial for Camel K 

### PR DESCRIPTION
**Pull request by weimeilin79**
Adding new serverless eventing tutorial for Camel K

### CODE REVIEW

**Comment by btannous** [comment]
looks like there are a few conflicts, I'll take a stab at this later this week. 
also will be moving this into a specific top level Serverless pathway instead of the current middleware one.

the folder and things can stay, no need to move them to make it happen.

**Comment by weimeilin79** [comment]
@btannous You can overwrite the conflicts. Most of them are updates on the spelling and updates on the version of OpenShift from 4.3 to 4.5. (And I also rewrite the whole eventing part). Can you please make a copy to Serverless? I need this one to also staying in the Camel K catalog too. Thanks!

**Comment by btannous** [comment]
Yes, it can be in both places!  And i will overwrite with your changes.

**Review by btannous — CHANGES_REQUESTED** [review]
First off, these are awesome scenarios.  Thank you for contributing!

after running through these I have some changes Id request before merging.

### In the **Basics**  scenario 

Step 4:

- The lab instructions are a little confusing: `For example, you can change the first endpoint (timer:java?period=3000) into the following: timer:java?period=60000 (1 minute between executions).`
  - I think it should mention that the student should be editing `Routing.java` somewhere here.

### In the **Serving**  scenario

- serving or eventing did not install automatically, i have a script to do this if you want to use it.
  - https://github.com/openshift-labs/learn-katacoda/blob/master/developing-on-openshift/serverless/assets/01-prepare/install-serverless.bash
  - There is this script and other files in that directory that are needed. This only installs serving, but I will be eventually updating it to also install eventing.

Step 2:

- There is a single code block that just says `log`
  - I think this should be `kamel log api` or maybe the previous step needs to add `—logs`?

### In the new **Eventing** scenario

- serving or eventing did not install automatically, i have a script to do this if you want to use it.
  - https://github.com/openshift-labs/learn-katacoda/blob/master/developing-on-openshift/serverless/assets/01-prepare/install-serverless.bash
  - There is this script and other files in that directory that are needed. This only installs serving, but I will be eventually updating it to also install eventing.

Step 2: 

- The line `$ kamel run --name simple-predictor -p predictor.name=simple camel-eventing/Predictor.java algorithms/SimpleAlgorithm.java -t knative-service.max-scale=1 --logs` does not run and errors with `Error: no matches for kind "Integration" in version "camel.apache.org/v1”`
  - Think it needs a `kamel install` step before doing anything

Step 3:

- the instructions say it to watch the logs after market-source.yaml but there was no `—logs` flag passed or separately running `kamel logs market-source`

**Review by btannous — APPROVED** [review]

**Pull request merged**
