### PR TITLE
Update scenario to work with kubefed v0.0.10

### PR DESCRIPTION
**Pull request by mvazquezc**

### CODE REVIEW

**Comment by cooktheryan** [comment]
:+1:

**Comment by BenHall** [comment]
Let me know when this is ready to merge...

**Comment by mvazquezc** [comment]
It can be merged. Thanks!

**Comment by mvazquezc** [comment]
@BenHall Something is not working properly on learn.openshift.com environment.

oc login https://$HOST1_IP:8443/ --insecure-skip-tls-verify=true -u admin -p admin
oc login https://$HOST2_IP:8443/ --insecure-skip-tls-verify=true -u admin -p admin

That used to work in the learn.openshift.com scenario (it worked on my environment https://www.katacoda.com/mvazquezc/courses/introduction/federated-clusters a few days ago)

Error:
image


Did something change?

**Comment by BenHall** [comment]
Let me check

**Comment by mvazquezc** [comment]
Now seems to be working

**Pull request merged**
