### PR TITLE
Update Openshift to 3.11 and Istio to 1.0.5

### PR DESCRIPTION
**Pull request by rafabene**
Hi @mhausenblas @marekjelen and @BenHall .

After this PR has been published, the environment openshift-3-11 needs to be rebuilt on learn.openshift.com and www.katacoda.com so I can work on the fixes for #366 and #367 

Thank you.

### CODE REVIEW

**Comment by rafabene** [comment]
Btw. At this moment, no istio scenario works. This PR will also fix all of them.

**Comment by BenHall** [comment]
@rafabene Thanks! To confirm, all Istio scenarios are now using `3.11` correct?

**Comment by rafabene** [comment]
That's right @BenHall

**Comment by rafabene** [comment]
@BenHall When the new environment will be rebuilt so I can work on the issues #366 and #367 ?  Thanks

**Pull request merged**
