### PR TITLE
[intro/prom-grafana]Make grafana route https

### PR DESCRIPTION
**Pull request by 4n4nd**
Add ssl cert warning instructions

### CODE REVIEW

**Review by btannous — APPROVED** [review]
lgtm.  would merge this now, but I think you guys are using it for devconf at the moment?

**Comment by 4n4nd** [comment]
@btannous Thanks! Just finished the workshop

**Comment by btannous** [comment]
hope it went well! have a good weekend !

**Comment by 4n4nd** [comment]
Thanks! it went well  :+1:

**Pull request merged**
